### ISSUE TITLE
Add requestId to the context

### ISSUE THREAD

**Issue by AlexisWalravens** [maou-shonen/hono-pino#28]
Hi,

Is there a way to get the request id from the injected context, se we could use it in responses ?
Like the basic [requestId](https://hono.dev/docs/middleware/builtin/request-id) middleware does ? 

Thanks!

**Comment by maou-shonen** [comment]
This isn’t supported at the moment,
but it's a good idea, and I'd be glad to add it!
One thing is, I feel like the request ID doesn’t quite belong inside the logger itself.

As an alternative, if you pass the `requestId` through the context,
the logger can pick it up automatically.
Here’s an example of how it could work:

```ts
import { Hono } from "hono";
import { pinoLogger } from "hono-pino";
import { requestId } from "hono/request-id";

const app = new Hono()
  .use(requestId()) // <-- Generate the request id using the official middleware
  .use(
    pinoLogger({
      http: {
        onReqMessage: (c) => "Request received",
      },
    }),
  )
  .get('/', (c) => c.text('hello world'));
```

How does that sound to you?

**Comment by AlexisWalravens** [comment]
Sure it makes total sense, just maybe it's not explicit enough that the requestId would be used automatically by pinoLogger, what do you think ?

**Comment by maou-shonen** [comment]
Don't worry,
I will use the referRequestIdKey option to describe this.
I like everything to be configurable :)

I will add this later.

**Comment by maou-shonen** [comment]
Published in https://github.com/maou-shonen/hono-pino/releases/tag/v0.5.0
