### ISSUE TITLE
bug: Compatibility Issue with Cloudflare Workers Global Scope Initialization

### ISSUE THREAD

**Issue by ZL-Asica** [maou-shonen/hono-pino#38]
**Description**:

While attempting to use `hono-pino` for logging in a Cloudflare Workers environment, I encountered the following error due to asynchronous operations being triggered within the global scope:
在 Cloudflare Workers 环境中使用 `hono-pino` 作为日志工具时，由于异步操作在全局作用域被触发，遇到了以下错误：

```bash
Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope.
```

The error arises when trying to use `pinoLogger` directly in the global scope, as shown below:
这个错误是因为 `pinoLogger` 在全局作用域中调用时触发的。以下代码会导致此错误：

```typescript
import { pinoLogger as logger } from 'hono-pino'

const app = new Hono<{ Bindings: Bindings }>()  // Bindings is Cloudflare Worker's Enviroment Variables

app.use(logger({
    pino: {
      level: 'debug',
    },
  }))
```

The issue is likely caused by asynchronous I/O operations or initialization within `hono-pino` or its dependencies. Cloudflare Workers restricts asynchronous operations within the global scope, and currently, `hono-pino` doesn’t handle this requirement.

**Suggested Solution**:

Consider refactoring `hono-pino` to delay or defer any asynchronous operations until the first request handler. Alternatively, providing an option to conditionally initialize the logger within a handler function could allow for compatibility with environments like Cloudflare Workers.
是否可以考虑优化 `hono-pino` 的异步操作，比如延迟异步操作的执行，或者提供一个选项将日志初始化放到第一个请求的 Handler 中？这样可以避免在全局作用域直接触发异步操作。

**Environment**:
- hono-pino version: [0.5.0]
- pino version: [9.5.0]
- Hono version: [4.6.8]
- Yarn version: [4.5.1]
- Cloudflare Workers environment

Thank you for looking into this compatibility issue!

非常感谢提供这样的 package，我用了 Hono 官网的[这个教程](https://hono.dev/docs/getting-started/cloudflare-workers)初始化的app，如果大佬需要复现可以直接初始化一个环境然后在这里面使用上面的代码进行测试。要提供更多的信息的话欢迎随时联系我！

**Comment by maou-shonen** [comment]
這很奇怪, 這個package沒有使用異步初始化
我檢查了依賴包也沒有
從零建立新CF worker環境dev、deploy都沒問題

![image](https://github.com/user-attachments/assets/84fb14ef-f814-483d-a3b9-4fb31921f07f)

光從你的敘述看起來, 建議你檢查一下入口檔案是否正確`export default app`
或是可以提供最小實現嗎?

**Comment by maou-shonen** [comment]
https://github.com/maou-shonen/hono-pino/releases/tag/v0.6.0 這個版本修復了一個會在cloudflare workers上發生錯誤的問題  
你可查看這個修復是否適用於你嗎?

**Comment by ZL-Asica** [comment]
感謝，我晚一些試一下
